### ISSUE TITLE
结果页数字显示存在精度丢失问题

### ISSUE THREAD

**Issue by qzx1991** [dolphindb/vscode-extension#2]
在使用vscode插件的时候，出现了精度丢失的问题

![image](https://user-images.githubusercontent.com/21259456/167049765-e26ae16c-af9c-44ef-abd9-32f41cbdf34e.png)

**Comment by ShenHongFei** [comment]
这个数据显然是插入数据的时候就不正确了
gui 可能在显示的时候自动截断了后面的显示
![企业微信截图_16518019517047](https://user-images.githubusercontent.com/15074472/167056532-ddd00f27-251c-4f73-aeef-f7e92ba0ecf5.png)
