### ISSUE TITLE
vscode插件显示不了数据和表结构

### ISSUE THREAD

**Issue by DengxiaoHong999** [dolphindb/vscode-extension#7]
vscode插件连接到本地库以后，可以看到本地存在哪些数据库,以及每个数据库存在哪些表，但是当想查看表前100条数据和查看表的结构时报错：peek_table error can't open file 系统找不到指定路径。我的数据库是放在E盘根目录的,但是显示查找的路径是D盘。

**Comment by peeyee** [comment]
你是不是迁移过数据了，导致元数据和时间路径不匹配。比如元数据里记录的位置是D盘，但是数据已经被你挪到E盘了。

**Comment by DengxiaoHong999** [comment]
> 你是不是迁移过数据了，导致元数据和时间路径不匹配。比如元数据里记录的位置是D盘，但是数据已经被你挪到E盘了。

我检查了一下，发现我以前数据库确实是在D盘，后来copy到E盘了。请问现在的情况需要我再copy回去还是有别的解决办法？

**Comment by peeyee** [comment]
这种方式不可行，再copy回去吧。
如果要在磁盘之间迁移数据，必须通过backupDB, 修改volumes路径， 然后restoreDB方式完成迁移。
